### ISSUE TITLE
Bikin API

### ISSUE THREAD

**Issue by ibnujakaria** [nafiesl/dompet#1]
Bikin API nya kang sapa tau ada yg mau bikin client app nya..

**Comment by nafiesl** [comment]
Siap, insyaallah kang @ibnujakaria, sambil jalan mau bikin API endpointnya.

**Comment by nafiesl** [comment]
Just info mas @ibnujakaria, sudah kita tambahkan API endpoint-endpointnya:

- List Transaksi 0efa902963fb6340a1c29be88140ad4561e110e5
- Entry Transaksi 28598a7f30b8a434e6cec608f4c0086654cb4c52
- Edit Transaksi dca69ff7dea8ed731135381092f629259024e7a6
- Hapus Transaksi a7726d788f4c1607193ade17db99f1a58a8d84e5

- Pengelolaan Data Kategori 054183bf8a7feb4dfa98057c22c0e883126aac6c
