### ISSUE TITLE
Apakah ini bug?

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#12]
Halo mas @nafiesl , makasih banyak sudah membuat repository ini. Saya sudah memakainya sejak bulan Februari dan sangat memuaskan serta menghemat waktu saya membuat sistem seperti ini. Ada yang ingin saya tanyakan tentang **saldo akhir** saat melakukan filter kategori. Jadi, saya melakukan filter kategori **dompet** dan saat di filter nilai **saldo akhir** rancu dengan nilai di **selisih**.

Kalau saya sebagai user akan condong memilih nilai di **selisih** karena valid dibandingkan **saldo akhir** saat di filter.

<img width="648" alt="screenshot 2019-02-19 at 9 13 30 pm" src="https://user-images.githubusercontent.com/11099186/53020542-0f6a3900-3492-11e9-9af7-3673bd9724e7.png">

**Comment by nafiesl** [comment]
Sama-sama mas @satyakresna semoga bermanfaat mas. :+1: 

Terkait problem ini, seharusnya saldo akhir sama dengan selisih ya mas? Karena saldo awalnya 0. Baik, akan saya akan cek lebih lanjut mas.

Terima kasih informasinya mas.

**Comment by satyakresna** [comment]
Iya mas betul. Semestinya begitu ketika di filter karena kalau tanpa filter nilai selisih sudah sesuai dengan nilai saldo akhir mas. Sama" mas, sukses selalu.

**Comment by nafiesl** [comment]
Ketemu mas problemnya, ternyata function balance yang digunakan untuk menghitung saldo itu hanya mempertimbangkan selisih dari tanggal awal s/d tanggal akhir yang dipilih. **Seharusnya** perhitungan saldo juga menyesuaikan kategori transaksi yang dipilih oleh user.

> Problem ini juga akan terjadi ketika kita melakukan filter dengan memilih **partner**.

Pada PR #14 ini, kita akan perbaiki problemnya. Nanti sekalian kita akan buat agar saldo memperhatikan **partner** yang dipilih oleh user.

Terima kasih.

**Comment by nafiesl** [comment]
mas @satyakresna barusan saya coba perbaiki problem ini di PR #14 kalau ada waktu mohon dibantu tes ya mas branch `fixing-balance-helper` nya. Kalau sudah oke, saya akan merge.

**Comment by satyakresna** [comment]
Halo mas @nafiesl , saya sudah cek dan masih ada bug di bagian kolom **Saldo Awal** di bawah waktu saya filter kategori transaksi saya yakni **Jenius**.

<img width="958" alt="screenshot 2019-03-02 at 8 28 52 pm" src="https://user-images.githubusercontent.com/11099186/53681826-e6fffb80-3d29-11e9-8fc4-7e0ba149ef7e.png">

Langkah-langkah untuk menghasilkan ini:

1. Mencari variable yang menghasilkan ini yakni di `resources/views/transactions/index.blade.php` seperti kodingan di bawah:
```php
<th class="text-right">
                            @php
                                $balance = 0;
                            @endphp
                            @if ($transactions->last())
                                {{ format_number($balance = balance(Carbon\Carbon::parse($transactions->last()->date)->subDay()->format('Y-m-d'))) }}
                            @else
                                0
                            @endif
                        </th>
```

2. Mencari nilai yang dihasilkan dari `$transactions->last()->date` yakni tanggal 6 Februari 2019.
3. Mencari nilai yang dihasilkan dari `Carbon\Carbon::parse($transactions->last->date)->subDay()->format('Y-m-d')` yakni "2019-02-05".
4. Mencari nilai yang dihasilkan dari fungsi `balance()` di `app/Helpers/functions.php` yakni Rp. 1,520,348.00. Query yang menghasilkan nilai ini adalah:
```
# Di sini terjadi bug karena tidak di set filter category nya
select * from transactions where date <= '2019-02-05';
```

**Comment by nafiesl** [comment]
Siap, terima kasih reviewnya mas @satyakresna. Akan saya cek lagi :+1:

**Comment by nafiesl** [comment]
mas @satyakresna, kalau ada waktu, mohon dibantu cek PR  #14 ini ya mas. Sudah coba saya tambahkan filter untuk function `balance` di `transations.index` berdasarkan `category_id` dan `partner_id` yang dipilih.

Terima kasih sebelumnya mas :pray:

**Comment by satyakresna** [comment]
Halo mas @nafiesl , saya sudah coba tetapi pas menjalankan fungsi `balance` di helper **functions.php** nilai dari `$categoryId` tetap `null` mas setelah saya coba jalankan perintah `dd()`. Apakah kalau kita set nilai `request('category_id')` maka fungsi `balance()` nilai yang tadi langsung dianggap null kah karena kita set`$categoryId = null`?

**Comment by satyakresna** [comment]
```
function balance($perDate = null, $startDate = null)
{
    $categoryId = request('category_id');
    $partnerId = request('partner_id');

    $transactionQuery = DB::table('transactions');
    if ($perDate) {
        $transactionQuery->where('date', '<=', $perDate);
    }
    if ($startDate) {
        $transactionQuery->where('date', '>=', $startDate);
    }
    if (isset($categoryId)) {
        $transactionQuery->where('category_id', $categoryId);
    }
    if (isset($partnerId)) {
        $transactionQuery->where('partner_id', $partnerId);
    }
    $transactions = $transactionQuery->where('creator_id', auth()->id())->get();

    return $transactions->sum(function ($transaction) {
        return $transaction->in_out ? $transaction->amount : -$transaction->amount;
    });
}
```

Kira" kalau bikin fungsi nya seperti itu gimana mas? Karena kalau di tes dengan fungsi ini hasilnya sudah benar.

<img width="935" alt="Screenshot 2019-03-20 at 6 28 33 PM" src="https://user-images.githubusercontent.com/11099186/54677507-fe1e5600-4b3d-11e9-9051-252c8a5b7665.png">

**Comment by nafiesl** [comment]
Terima kasih mas @satyakresna, saya sudah coba function itu, sepertinya ga cocok juga.

Pendapat saya begini mas.
1. Summary saldo awal, dan saldo akhir ini hanya cocok untuk list transaksi tanpa filter kategori dan partner (perhitungan balance benar).
2. Saldo yang benar adalah saldo per hari itu. Ketika difilter per kategori, perhitungannya beda lagi.

solusinya menurut saya begini:
1. Ketika list transaksi difilter tanggal, bulan dan tahun, summary saldo muncul
2. Ketika list transaksi difilter dengan kategori dan partner, summary saldo disembunyikan
3. Ketika list transaksi difilter dengan kategori dan partner, cukup tampil total keluar, total masuk dan selisih.

Kira-kira begitu solusinya mas.

**Comment by satyakresna** [comment]
Hai mas @nafiesl, saya pikir solusi mas cocok utk diimplementasikan.

**Comment by nafiesl** [comment]
Oke mas, nanti saya eksekusi. Terima kasih banyak report dan bantuannya mas @satyakresna.
