### ISSUE TITLE
[Feedback] Sebaiknya pakai input type number

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#13]
Halo mas @nafiesl , saya ada umpan balik tentang menginputkan jumlah nominal pengeluaran dan transaksi. Sebaiknya menggunakan `input type=number` karena sudah pasti berkaitan dengan angka. Saya melihat mas menggunakan Laravel form collective buatan sendiri yang sintaks terkaitnya seperti ini: `{!! FormField::price('amount', ['required' => true, 'label' => __('transaction.amount')]) !!}`. Tetapi, saat dirender di browser hasilnya malah input type text.

Kalau saya menggunakan laptop mungkin tidak ada masalah. Tetapi, kalau menggunakan mobile akan terasa merepotkan karena harus mengubah opsi dari alphabet ke angka seperti di screenshot.
![photo_2019-02-19 22 10 25](https://user-images.githubusercontent.com/11099186/53021008-2c533c00-3493-11e9-9e70-7d9632fa54d0.jpeg)

**Comment by nafiesl** [comment]
Ah. I see, solusinya, nanti kita bisa buat field itu mengunakan tag input html biasa mas.
Jadi sebelumnya pakai `FormField::price()` akan diganti dengan `<input type=number>`.

Terima kasih feedbacknya mas. Sangat membantu :+1:

**Comment by satyakresna** [comment]
Sama" mas. Senang saya bisa membantu. Untuk kasus ini mau mas @nafiesl follow up atau boleh saya bantu follow up? Follow up dalam artian buat pull request.

**Comment by nafiesl** [comment]
Boleh pull request mas. Silakan.
