### ISSUE TITLE
Apakah ini juga bug? #2

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#16]
Halo mas @nafiesl , saya ada kesulitan ketika saldo pemasukan saya dari bulan Februari (gabungan kategori **dompet**, **Jenius**, dan **Saldo bank BNI**) malah direset dari nol di bulan Maret. Jadi, saya kesulitan untuk memastikan saldo saya per hari ini berdasarkan kategori **dompet** (dengan bantuan filter) lagi berapa.

<img width="1437" alt="screenshot 2019-03-01 at 9 38 30 pm" src="https://user-images.githubusercontent.com/11099186/53641819-11d74a80-3c6b-11e9-84fd-fbcabf7191c5.png">

**Comment by nafiesl** [comment]
Untuk Total pemasukan dan pengeluaran, itu dihitung dari total transaksi yang tampil di layar itu mas.
Disitu terlihat total transaksi pemasukan tidak ada, tetapi pengeluaran 5 transaksi.

Jadi:
1. Total pemasukan adalah total pemasukan dari semua transaksi yang tampil.
2. Total pengeluaran adalah total pengeluaran dari semua transaksi yang tampil.

Sedangkan saldo awal maret yang mas maksud, ada di baris **Saldo Awal** di bawah list transaksi ini.

![53641819-11d74a80-3c6b-11e9-84fd-fbcabf7191c5](https://user-images.githubusercontent.com/8721551/53643462-1271e000-3c6f-11e9-9697-46f410f737fe.png)

**Comment by satyakresna** [comment]
Halo mas, padahal ekspektasi saya adalah saldo yang senilai 383.754 itu masuk ke kolom **Total pemasukan** dan tidak direset dari nol. Mungkin ini kita follow up kalau kasus di bug pertama sudah beres. Terima kasih mas dan maaf sebelumnya merepotkan.

**Comment by satyakresna** [comment]
Halo mas @nafiesl , setelah saya pikir dan lihat kembali transaksi di aplikasi dompet ternyata sudah benar sesuai alur dan ternyata bukan bug untuk issue ini. Saya close ya. Trima kasih.

**Comment by nafiesl** [comment]
Oke mas terima kasih.
