### ISSUE TITLE
Menghapus kategori

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#18]
Halo mas @nafiesl , apakah saat membuat suatu kategori yang sudah terisi transaksinya tidak bisa dihapus ya dari sistem? Karena ada kategori yang ingin saya hapus. Trims.

**Comment by nafiesl** [comment]
Betul mas, di class Policy nya sudah dibuat seperti itu [CategoryPolicy.php#L58-L62](https://github.com/nafiesl/dompet/blob/master/app/Policies/CategoryPolicy.php#L58-L62). Tujuannya agar transaksi tidak error ketika kategorinya dihapus.

Atau mas @satyakresna ada masukan terkait hal ini?

**Comment by satyakresna** [comment]
Kalau dari saya saat ini lagi ingin menghapus kategori transaksi **Jenius** di aplikasinya, hanya saja sudah ada daftar transaksi walaupun hanya sekitar 10 baris. Cuma, saya rada malas kalau hapus satu per satu. Bagaimana kalau kita menghapus sebuah kategori yang sudah ada transaksi tetapi tidak benar" dihapus di database alias ada bantuan soft deletenya?

**Comment by nafiesl** [comment]
Bisa sih, cuman mengubah struktur table lagi ya.

Gimana kalau gini: Kita kasih **checbox** "Hapus bersama transaksinya" saat mau hapus kategori. Secara umum kira-kira begini:
1. Fitur hapus kategori dibuka (walapun ada transaksi).
2. Tampil informasi jumlah transaksi pada kategori ini
3. Checkbox "Hapus semua transaksinya".
4. Jika checbox dicentang, maka semua transaksinya ikut dihapus.
5. Jika checbox tidak dicentang, maka semua transaksi diset `null` pada kolom category_id nya.

How about it, mas?

**Comment by satyakresna** [comment]
Saya lihat itu ide yang bagus mas. Kita bisa coba ini.

**Comment by nafiesl** [comment]
Mau coba contribute dengan PR mas @satyakresna? Hehe..

**Comment by satyakresna** [comment]
Oh oke, saya mau coba. :D

**Comment by nafiesl** [comment]
Terima kasih sebelumnya mas. :pray:

**Comment by satyakresna** [comment]
Sip, sama" mas.

**Comment by nafiesl** [comment]
mas @satyakresna, issue ini sudah bisa kita closed dengan PR #21 yang sudah merged. :+1:
