### ISSUE TITLE
[TANYA] Seputar autentikasi dan permasalahan logout

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#24]
Halo mas @nafiesl , saya cek di API nya tidak ada route untuk logout. Saya pikir kalau untuk urusan autentikasi bisa menggunakan Laravel passport di [mode grant type password](https://laravel.com/docs/5.8/passport#password-grant-tokens). Mengapa saya mengusulkan ini? Ini bertujuan utk memisahkan back-end dan front-end. Saya ingin mencoba membuat web apps untuk dompet dan autentikasinya bersifat stateless.

Btw, saya terinspirasi usul ini setelah mencoba tutorial yang disediakan oleh Andre Madarang di Youtube. Ia membuat semacam todo web apps dengan Vue (front-end) dengan menggunakan Laravel Passport sebagai autentikasinya. Mungkin bisa disimak di [daftar putar ini](https://www.youtube.com/playlist?list=PLEhEHUEU3x5q-xB1On4CsLPts0-rZ9oos) mulai dari daftar ke 9 - 11.

**Comment by nafiesl** [comment]
Halo mas @satyakresna, usul yang bagus sekali mas. Senang sekali jika mas rencana mau membuat client app untuk project dompet ini, karena API memang sudah tersedia (walaupun mungking perlu dikembangkan lagi).

Kebetulan saya masih kurang familiar dengan passport, apakah mas @satyakresna bisa bantu buat PR untuk fitur login dengan passport ini?

Terima kasih sebelumnya.

**Comment by satyakresna** [comment]
Halo mas, oke siap saya coba bantu. Mungkin saya butuh bantuan dari mas utk
koreksi unit test yg saya buat karena saya blm mahir buat unit test. He he
he.

**Comment by nafiesl** [comment]
Ok siap, ga apa2 mas. Tanpa test dulu, nanti saya ulik juga untuk bikin testnya di passport, kebetulan ini, saya belum pernah juga :grin: 

Terima kasih bantuannya mas :pray:

**Comment by nafiesl** [comment]
Terima kasih untuk batuan PR improvement dengan Laravel Passportnya mas @satyakresna, senang sekali dengan kontribusi ini. :pray:

**Comment by satyakresna** [comment]
Terima kasih kembali mas. Senang sekali saya bisa diberikan kesempatan
untuk berkontribusi lewat repository mas Nafies

Salam,
Satya Kresna

https://github.com/satyakresna
www.linkedin.com/in/satyakresna
