### ISSUE TITLE
[RF] Add ability to manage loan

### ISSUE THREAD

**Issue by ad3n** [nafiesl/dompet#43]
Akan sangat membantu sekali kita ada fitur management utang/piutang

**Comment by nafiesl** [comment]
Mas @ad3n, kalau kita buat table `loans`, kira-kira attribute/kolomnya gini ya:
```
id int(10) unsigned auto increment
partner_id int(10) unsigned
in_out tinyint(1)
amount decimal(12, 2) unsigned
planned_payment_count int(10) unsigned default 1
closed_at
created_at
updated_at 
```
Gimana mas?

**Comment by nafiesl** [comment]
Keterangan:
`in_out` itu isinya `0` dan `1`.
Kalau `0` berarti pengeluaran, artinya piutang kita ke orang lain (partner).
Kalau `1` berarti pemasukan, artinya hutang kita ke orang lain (partner).

Jadi fitur "Loans" ini, bisa mencatat hutang orang ke kita, atau hutang kita ke orang lain mas @ad3n.

**Comment by ad3n** [comment]
Mantap mas, betul seperti itu kira-kira

**Comment by nafiesl** [comment]
Ok, kita grooming dulu mas fiturnya.

Kemudian di tabel `transactions` kita perlu tambah kolom:
```
loan_id int(10) unsigned nullable
```
Jika null, berarti transaksi biasa, tapi jika tidak null, berarti transaksi itu terkait pembayaran hutang piutang.

**Comment by nafiesl** [comment]
1,5 tahun kemudian....

Halo mas @ad3n, ini fitur manage loannya sudah jadi. Udah telat banget, haha..
Ga apa-apa lah ya, siapa tahu yang lain ada yang butuh. Makasih mas @ad3n.

**Daftar Pinjaman**

![screen_2021-02-16_004](https://user-images.githubusercontent.com/8721551/108072763-433cc100-70a2-11eb-85a2-f0c16e2e7ba8.jpg)

**Detail Pinjaman**

![screen_2021-02-16_005](https://user-images.githubusercontent.com/8721551/108072784-49cb3880-70a2-11eb-9913-0237481ad894.jpg)

**Input Pinjaman Baru**

![screen_2021-02-16_006](https://user-images.githubusercontent.com/8721551/108072798-4df75600-70a2-11eb-8f7a-76d1f2420642.jpg)

**Comment by ad3n** [comment]
mantap sekali mas... keren banget
