### ISSUE TITLE
Some deprecation/abandonment warnings when installing with Composer

### ISSUE THREAD

**Issue by Maikuolan** [nafiesl/dompet#51]
Some deprecation/abandonment warnings when installing with Composer

```
$ php composer.phar update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 106 installs, 0 updates, 0 removals
...
...(omitted for readability)...
...
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
```

Next, to check which dependencies are causing these warnings.

```
$ php composer.phar why zendframework/zend-diactoros
laravel/passport  v7.5.1  requires  zendframework/zend-diactoros (~1.0|~2.0)
```

*Referring to: https://github.com/laravel/passport/issues/1167*

Checking the history of their dependencies, it seems they've replaced zendframework/zend-diactoros with laminas/laminas-diactoros at this commit here: https://github.com/laravel/passport/commit/7ec6e58fa4f08a19dc04ea9abf206d87b9462f43#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R30-R33

So, updating dompet's laravel/passport dependency from ^7.3 to at least 8.2.0 or newer should resolve the warning for that dependency.

```
$ php composer.phar why jakub-onderka/php-console-highlighter
psy/psysh  v0.9.12  requires  jakub-onderka/php-console-highlighter (0.3.*|0.4.*)

$ php composer.phar why jakub-onderka/php-console-color
jakub-onderka/php-console-highlighter  v0.4  requires  jakub-onderka/php-console-color (~0.2)
```

*Referring to: https://github.com/bobthecow/psysh/issues/624*

Checking the history of their dependencies, it seems they've fixed the problem at this commit here (>= v0.10.3): https://github.com/bobthecow/psysh/commit/2a7589525ee6583eb6a06d23db2e791b37dd44b6#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

But.. dompet doesn't directly list psy/psysh as a dependency anyway, so we'll need to dig a little further:

```
$ php composer.phar why psy/psysh
laravel/tinker  v1.0.10  requires  psy/psysh (0.7.*|0.8.*|0.9.*)
```

Checking the history of their dependencies, it seems they've fixed the problem at this commit here: https://github.com/laravel/tinker/commit/db9a3ec4eb4a9c49b5ad56a72953ae297a1fb511#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L17-R22

So, updating dompet's laravel/passport dependency from ^1.0 to at least v2.4.0 or newer should resolve the warning for that dependency.

*Note: I haven't checked compatibility between dompet and these newer dependencies, so that should be confirmed before changing anything.*

I hope this information helps. :-)

**Comment by nafiesl** [comment]
Hi @Maikuolan, thank you for your time for writing this. I will check these dependency issue.
