### ISSUE TITLE
Unable to prepare route [change-password] for serialization. Another route has already been assigned name [password.change].

### ISSUE THREAD

**Issue by satyakresna** [nafiesl/dompet#55]
Halo mas @nafiesl, pada saat saya mencoba menjalankan perintah `php artisan optimize`, route change-password tidak bisa digunakan. Kalau saya lihat dari error log nya saya menduga bahwa route change-password sudah hanya bisa di pakai satu kali saja.

Berikut gambar pesan error nya:

<img width="906" alt="Screen Shot 2020-09-05 at 13 13 25" src="https://user-images.githubusercontent.com/11099186/92298300-e331e280-ef79-11ea-9252-784a69304b6a.png">

Sepertinya penyebabnya ada di `routes/web.php`:

```
// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show')->name('password.change');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');
```

**Comment by satyakresna** [comment]
Mas @nafiesl, permasalahan di atas sudah berhasil saya selesaikan. Dugaan saya keliru, saya pikir masalahnya ada di **$uri** (`'change-password'`) ternyata masalahnya ada di named routes yakni `password.change`. Di Laravel versi 7 mengatakan bahwa named routes harus unik seperti yang dijelaskan di dokumentasi: https://laravel.com/docs/7.x/routing#named-routes. 

Jadi, saya pikir untuk menghapus named routes `password.change` di bagian `Route::get('change-password')` dan membiarkan named routes `password.change` di bagian `Route::path('change-password')`.

```diff
-Route::get('change-password', 'Auth\ChangePasswordController@show')->name('password.change');
+Route::get('change-password', 'Auth\ChangePasswordController@show');
```

Saya akan kirimkan PR nya.

**Comment by nafiesl** [comment]
PRnya sudah merged mas @satyakresna. Makasih banyak bantuannya mas :bow: 

Maaf saya slow response 3 minggu terakhir karena hectic kerjaan di kantor :sweat_smile:

**Comment by satyakresna** [comment]
Tidak apa" mas. Semoga pekerjaannya lancar terus! 🙏

**Comment by nafiesl** [comment]
Thank you mas @satyakresna
